
["Common configs"]
	#Set this to false to disable the repair of the item enchanted with Indestructible
	"Repair when enchanted:" = true
	#Set this to true to enable the enchantment on books
	"Allowed on books:" = true
	#Set this to true to enable finding the enchantment on loot chests
	"Allowed in chest:" = false
	#Set this to true to enable finding the enchantment in villager trades
	"Allowed in villager trades:" = false

